# Form implementation generated from reading ui file 'designer_ui/main_frame.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(914, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setContentsMargins(0, 9, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sign_in_by_login_button = QtWidgets.QPushButton(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_in_by_login_button.sizePolicy().hasHeightForWidth())
        self.sign_in_by_login_button.setSizePolicy(sizePolicy)
        self.sign_in_by_login_button.setMinimumSize(QtCore.QSize(0, 400))
        self.sign_in_by_login_button.setMaximumSize(QtCore.QSize(16777215, 16666666))
        self.sign_in_by_login_button.setObjectName("sign_in_by_login_button")
        self.horizontalLayout.addWidget(self.sign_in_by_login_button)
        self.sign_in_by_biometric_button = QtWidgets.QPushButton(parent=Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_in_by_biometric_button.sizePolicy().hasHeightForWidth())
        self.sign_in_by_biometric_button.setSizePolicy(sizePolicy)
        self.sign_in_by_biometric_button.setMinimumSize(QtCore.QSize(0, 400))
        self.sign_in_by_biometric_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sign_in_by_biometric_button.setStyleSheet("  border-left: 1px solid rgb(255, 255, 255);")
        self.sign_in_by_biometric_button.setObjectName("sign_in_by_biometric_button")
        self.horizontalLayout.addWidget(self.sign_in_by_biometric_button)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.sign_in_by_login_button.setText(_translate("Frame", "Вход по логину"))
        self.sign_in_by_biometric_button.setText(_translate("Frame", "Вход по биометрии"))
