# Form implementation generated from reading ui file './designer_ui/sign_in_by_login_frame.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1044, 516)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(335, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_login = QtWidgets.QLabel(parent=Frame)
        self.label_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_login.setObjectName("label_login")
        self.verticalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(parent=Frame)
        self.lineEdit_login.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.label_password = QtWidgets.QLabel(parent=Frame)
        self.label_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Frame)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.enter_pushbutton = QtWidgets.QPushButton(parent=Frame)
        self.enter_pushbutton.setMinimumSize(QtCore.QSize(0, 40))
        self.enter_pushbutton.setStyleSheet("border-radius: 10px;\n"
"border-right: 1px solid rgb(255, 255, 255);\n"
"border-left: 1px solid rgb(255, 255, 255);")
        self.enter_pushbutton.setObjectName("enter_pushbutton")
        self.verticalLayout.addWidget(self.enter_pushbutton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(335, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_login.setText(_translate("Frame", "Логин"))
        self.label_password.setText(_translate("Frame", "Пароль"))
        self.enter_pushbutton.setText(_translate("Frame", "Войти"))
